name: Build Distribution Package

on:
  workflow_call:
    inputs:
      CURRENT_PACKAGE_VERSION:
        description: 'Current package version'
        required: true
        type: string
      NEW_PACKAGE_VERSION:
        description: 'New package version'
        required: true
        type: string

permissions:
  contents: read

jobs:
  update-pyproject-toml:
    name: Update pyproject.toml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update package version in pyproject.toml
        run: |
          sed -i "s+version = \"${{ inputs.CURRENT_PACKAGE_VERSION }}\"+version = \"${{ inputs.NEW_PACKAGE_VERSION }}\"+g" pyproject.toml

      - name: Upload updated pyproject.toml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyproject-toml
          path: pyproject.toml
#
#  build-wheels:
#    name: Build wheels on ${{ matrix.os }}
#    needs: [update-pyproject-toml]
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-24.04]
##        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-14, windows-2022, windows-11-arm]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Download updated pyproject.toml
#        uses: actions/download-artifact@v4
#        with:
#          name: pyproject-toml
#
#      - name: Build wheels
#        uses: pypa/cibuildwheel@v2.20.0
#
#      - name: Upload distributions
#        uses: actions/upload-artifact@v4
#        with:
#          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
#          path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution
    needs: [update-pyproject-toml]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
