name: CI Scripts

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Test scripts

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts-requirements.txt

      - name: Run tests scripts
        run: pytest scripts -v -s --doctest-modules --cov=scripts --log-level=WARNING --color=yes
