name: CI

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

#      - name: Compile shared library on Linux or macOS
#        if: runner.os != 'Windows'
#        run: g++ -fPIC -Wall -Wextra -shared -o tradeflow/libcpp.${{ matrix.os == 'macos-latest' && 'dylib' || 'so' }} lib/cpp/simulation.cpp -std=c++17
#
#      - name: Compile shared library on Windows
#        if: runner.os == 'Windows'
#        run: g++ -Wall -Wextra -shared -o tradeflow/libcpp.dll lib/cpp/simulation.cpp -std=c++17

      - name: make
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: pytest -v -s --doctest-modules --cov=tradeflow --log-level=WARNING --color=yes
