name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - '**'

jobs:
  run-tests:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: "Configure CMake Build System"
        run: cmake -S . -B build -DMY_PROJECT_SOURCE_DIR="." -DCMAKE_BUILD_TYPE=Debug

      - name: "Build Project"
        run: cmake --build build --config Debug

      - name: Run tests
        run: pytest tradeflow -v -s --doctest-modules --cov=tradeflow --log-level=WARNING --color=yes
