name: CI

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Compile C++
#        run: g++ -fPIC -Wall -Wextra -shared -o tradeflow/simulate.so tradeflow/simulate.cpp -std=c++17

      - name: Compile shared library on Linux or macOS
        if: runner.os != 'Windows'
        run: g++ -fPIC -Wall -Wextra -shared -o tradeflow/libcpp.${{ matrix.os == 'macos-latest' && 'dylib' || 'so' }} tradeflow/simulate.cpp -std=c++17

      - name: Compile shared library on Windows
        if: runner.os == 'Windows'
        run: |
          g++ -Wall -Wextra -shared -o tradeflow/libcpp.dll tradeflow/simulate.cpp -std=c++17

      - name: Run tests
        run: pytest -v -s --doctest-modules
