name: Publish to PyPi

on:
  workflow_call:
    inputs:
      PACKAGE_VERSION:
        description: 'Package version'
        required: true
        type: string
      NEW_PACKAGE_VERSION:
        description: 'New package version'
        required: true
        type: string
      package-index:
        description: 'Package index'
        required: true
        type: string

permissions:
  contents: write

jobs:
  update-pyproject-toml:
    name: Update pyproject.toml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace package version in pyproject.toml
        run: |
          sed -i "s+version = \"${{ inputs.PACKAGE_VERSION }}\"+version = \"${{ inputs.NEW_PACKAGE_VERSION }}\"+g" pyproject.toml

      - name: Upload updated pyproject.toml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyproject-toml
          path: pyproject.toml

  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [update-pyproject-toml]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
#        ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution
    needs: [update-pyproject-toml]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload-pypi:
    name: Upload package to PyPi
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/tradeflow

    permissions:
      id-token: write

    steps:
      - name: Unpacks all CIBW artifacts into dist/
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: display package index
        run: |
          echo "Package index: ${{ inputs.package-index }}"

      - name: Publish release distributions to PyPI
        if: ${{ inputs.package-index == 'pypi' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/

      - name: Publish release distributions to Test PyPI
        if: ${{ inputs.package-index == 'test.pypi' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
