name: Publish to PyPi

on:
  workflow_call:
    inputs:
      package-index:
        description: 'Package index'
        required: true
        type: string

permissions:
  contents: write

jobs:
  upload-pypi:
    name: Upload package to PyPi
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/tradeflow

    permissions:
      id-token: write

    steps:
      - name: Unpacks all CIBW artifacts into dist/
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish release distributions to PyPI
        if: ${{ github.event.inputs.package-index == 'pypi' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/

      - name: Publish release distributions to Test PyPI
        if: ${{ github.event.inputs.package-index == 'test.pypi' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
