name: PyPi Verify

on:
  push:
  workflow_dispatch:

jobs:
  pypi:
    name: Verify PyPi

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run script
        run: python scripts/pypi.py test.pypi
#        run: python -m scripts.pypi.pypi-verify pypi
