name: Upload Python Package

on:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload-testpypi:
    needs: [build-wheels, build-sdist]

    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/tradeflow

    permissions:
      id-token: write

    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish release distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  verify-test-pypi:
    name: Run PyPi Verify script on index Test PyPi

    needs: [upload-testpypi]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts-requirements.txt

      - name: Add package directory to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run script
        run: python scripts/pypi_verify.py test.pypi

  upload-pypi:
    needs: [build-wheels, build-sdist, upload-testpypi, verify-test-pypi]

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/tradeflow

    permissions:
      id-token: write

    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/

  verify-pypi:
    name: Run PyPi Verify script on index PyPi

    needs: [upload-pypi]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts-requirements.txt

      - name: Add package directory to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run script
        run: python scripts/pypi_verify.py pypi
