name: Verify Uploaded Package Content

on:
  workflow_call:
    inputs:
      package-index:
        description: 'Package index'
        required: true
        type: string
      package-version:
        description: 'Package version'
        required: true
        type: string

jobs:
  run-script:
    name: Run script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts-requirements.txt

      - name: Run script
        run: python -m scripts.pypi_verify_uploaded_content ${{ inputs.package-index }} ${{ inputs.package-version }}
